name: Test Build Ubuntu
on:
  push:
    branches:
      - master

jobs:
  build_vim3_legacy_kernel_images:
    name: Build VIM3 Legacy Kernel Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Fetch Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y make lsb-release qemu-user-static zip

      # Get current date
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +%F | sed 's/-//g')"

      # Build
      - name: Build Image
        run: |
          .github/workflows/build.sh legacy VIM3 Ubuntu

      # Upload Images to GitHub Actions Artifacts
      - name: 'Upload VIM3 Ubuntu Minimal Legacy Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3-Ubuntu-Minimal-Legacy-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-minimal-*.img.xz
      - name: 'Upload VIM3 Debian Packages for Legacy Kernel'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3-Debian-Packages-Legacy-Kernel-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/debs/
